name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Create virtual environment
        run: python -m venv ${GITHUB_WORKSPACE}/.venv

      - name: Activate virtual environment and install dependencies
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          python -m pip install --upgrade pip
          pip install uv
          uv pip install . --extra dev -r pyproject.toml

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Activate virtual environment
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate

      - name: Run Pylint
        run: |
          source ${GITHUB_WORKSPACE}/.venv/bin/activate
          pylint my_python_project tests

      - name: Run Flake8
        run: |
          flake8 my_python_project tests

      - name: Run MyPy
        run: |
          mypy my_python_project

      - name: Run Black
        run: |
          black --check my_python_project tests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Activate virtual environment
        run: |
          source .venv/bin/activate

      - name: Run tests with coverage
        run: |
          pytest --cov=my_python_project --cov-report=xml --cov-report=term-missing --cov-report=xml:coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}